base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

    path('update-user/', views.updateUser, name="update-user"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)
    

class User(AbstractUser):
    # username = None
    name = models.CharField(max_length=200, null=True, help_text="Nhập tên của bạn", verbose_name="Tên")
    email = models.EmailField(unique=True, null=True, help_text="Nhập email của bạn", verbose_name="Email")
    bio = models.TextField(null=True, help_text="Giới thiệu ngắn về bản thân", verbose_name="Tiểu sử")
    avatar = models.ImageField(null=True, default="avatar.svg", help_text="Tải lên ảnh đại diện", verbose_name="Ảnh đại diện")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email


class Topic(models.Model):
    name = models.CharField(max_length=200, help_text="Nhập tên chủ đề", verbose_name="Chủ đề")

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, help_text="Chọn người tạo phòng", verbose_name="Người tạo phòng")
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True, help_text="Chọn chủ đề cho phòng", verbose_name="Chủ đề")
    name = models.CharField(max_length=200, help_text="Nhập tên phòng", verbose_name="Tên phòng")
    description = models.TextField(null=True, blank=True, help_text="Nhập mô tả phòng", verbose_name="Mô tả")
    participants = models.ManyToManyField(User, related_name='participants', blank=True, help_text="Chọn thành viên tham gia", verbose_name="Thành viên")
    updated = models.DateTimeField(auto_now=True, help_text="Thời gian cập nhật cuối", verbose_name="Cập nhật lúc")
    created = models.DateTimeField(auto_now_add=True, help_text="Thời gian tạo phòng", verbose_name="Tạo lúc")

    class Meta:
        ordering = ['-updated', '-created']
        verbose_name = "Phòng"
        verbose_name_plural = "Các phòng"

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Người gửi", verbose_name="Người dùng")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, help_text="Phòng gửi tin nhắn", verbose_name="Phòng")
    body = models.TextField(help_text="Nội dung tin nhắn", verbose_name="Tin nhắn")
    updated = models.DateTimeField(auto_now=True, help_text="Thời gian cập nhật tin nhắn", verbose_name="Cập nhật lúc")
    created = models.DateTimeField(auto_now_add=True, help_text="Thời gian tạo tin nhắn", verbose_name="Tạo lúc")

    class Meta:
        ordering = ['-updated', '-created']
        verbose_name = "Tin nhắn"
        verbose_name_plural = "Các tin nhắn"

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room, User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']



class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .models import Room, Topic, Message, User
from .forms import RoomForm, UserForm, MyUserCreationForm


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'Người dùng không tồn tại')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Email hoặc mật khẩu không đúng')

    context = {'page': page}
    return render(request, 'base/login_register.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home')


def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Đã xảy ra lỗi khi đăng ký')

    return render(request, 'base/login_register.html', {'form': form})


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()
    room_messages = Message.objects.filter(
        Q(room__topic__name__icontains=q))[0:3]

    context = {'rooms': rooms, 'topics': topics,
               'room_count': room_count, 'room_messages': room_messages}
    return render(request, 'base/home.html', context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all()
    participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('room', pk=room.id)

    context = {'room': room, 'room_messages': room_messages,
               'participants': participants}
    return render(request, 'base/room.html', context)


def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user': user, 'rooms': rooms,
               'room_messages': room_messages, 'topics': topics}
    return render(request, 'base/profile.html', context)


@login_required(login_url='login')
def createRoom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        return redirect('home')

    context = {'form': form, 'topics': topics}
    return render(request, 'base/room_form.html', context)


@login_required(login_url='login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    if request.user != room.host:
        return HttpResponse('Bạn không có quyền truy cập trang này!')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('home')

    context = {'form': form, 'topics': topics, 'room': room}
    return render(request, 'base/room_form.html', context)


@login_required(login_url='login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('Bạn không có quyền truy cập trang này!')

    if request.method == 'POST':
        room.delete()
        return redirect('home')
    return render(request, 'base/delete.html', {'obj': room})


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('Bạn không có quyền truy cập trang này!')

    if request.method == 'POST':
        message.delete()
        return redirect('home')
    return render(request, 'base/delete.html', {'obj': message})


@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user-profile', pk=user.id)

    return render(request, 'base/update-user.html', {'form': form})


def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'base/topics.html', {'topics': topics})


def activityPage(request):
    room_messages = Message.objects.all()
    return render(request, 'base/activity.html', {'room_messages': room_messages})

base/templates/base/activity_component.html
<div class="activities">
    <div class="activities__header">
        <h2>Hoạt động gần đây</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}} trước</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>xóa</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}

        </div>
        <div class="activities__boxContent">
            <p>đã trả lời bài viết “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
            <div class="activities__boxRoomContent">{{message.body}}</div>
        </div>
    </div>
    {% endfor %}

</div>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Quay lại</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Bạn có chắc chắn muốn xóa "{{obj}}" không?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Xác nhận" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/delete_old.html
{% extends 'main.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p>Bạn có chắc chắn muốn xóa "{{obj}}" không?</p>

    <a href="{{request.META.HTTP_REFERER}}">Quay lại</a>
    <input type="submit" value="Xác nhận" />
</form>

{% endblock content %}

base/templates/base/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>
{% endfor %}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}

<main class="layout layout--3">
  <div class="container">

    <!-- Topics Start -->
    {% include 'base/topics_component.html' %}

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Tìm kiếm bài viết" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Chủ đề</a>
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Hoạt động gần đây</a>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Phòng thảo luận</h2>
          <p>Có {{room_count}} phòng đang hoạt động</p>
        </div>

        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">
            </path>
          </svg>
          Tạo phòng mới
        </a>
      </div>

      {% include 'base/feed_component.html' %}

    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}

    <!-- Activities End -->
  </div>
</main>

{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %}

{% block content %}
<main class="auth layout">

  {% if page == 'login' %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Đăng nhập</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Web hỏi đáp</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Email</label>
            <input id="username" name="email" type="email" placeholder="Ví dụ: tenban@email.com" />
          </div>
          <div class=" form__group">
            <label for="password">Mật khẩu</label>
            <input id="password" name="password" type="password"
              placeholder="Nhập mật khẩu" />
          </div>

          <button class="btn btn--main" type="submit">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
              </path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
              </path>
            </svg>

            Đăng nhập
          </button>
        </form>

        <div class="auth__action">
          <p>Bạn chưa có tài khoản?</p>
          <a href="{% url 'register' %}" class="btn btn--link">Đăng ký</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Đăng ký</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Web hỏi đáp</h2>

        {% comment %} <form class="form" action="" method="POST">
          {% csrf_token %}

          {% for field in form %}
          <div class="form__group form__group">
            <label for="room_name">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}


          <button class="btn btn--main" type="submit">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
              </path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
              </path>
            </svg>

            Đăng ký
          </button>
        </form> {% endcomment %}
        <form class="form" action="" method="POST">
  {% csrf_token %}
  <div class="form__group">
    <label for="id_name">Tên</label>
    {{ form.name }}
  </div>
  <div class="form__group">
    <label for="id_username">Tên đăng nhập</label>
    {{ form.username }}
  </div>
  <div class="form__group">
    <label for="id_email">Email</label>
    {{ form.email }}
  </div>
  <div class="form__group">
    <label for="id_password1">Mật khẩu</label>
    {{ form.password1 }}
  </div>
  <div class="form__group">
    <label for="id_password2">Xác nhận mật khẩu</label>
    {{ form.password2 }}
  </div>
  <button type="submit" class="btn btn--main" style="margin-top: 20px;">
    <i class="fa fa-lock"></i> Đăng ký
  </button>
</form>

        <div class="auth__action">
          <p>Bạn đã có tài khoản?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Đăng nhập</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</main>
{% endblock content %}

base/templates/base/login_register_old.html
{% extends 'main.html' %}

{% block content %}


{% if page == 'login' %}
<div>
    <form method="POST" action="">
        {% csrf_token %}

        <label>Tên đăng nhập:</label>
        <input type="text" name="username" placeholder="Nhập tên đăng nhập" />

        <label>Mật khẩu:</label>
        <input type="password" name="password" placeholder="Nhập mật khẩu" />

        <input type="submit" value="Đăng nhập" />
    </form>

    <p>Bạn chưa có tài khoản?</p>
    <a href="{% url 'register' %}">Đăng ký</a>
</div>

{% else %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Đăng ký" />
    </form>
    <p>Bạn đã có tài khoản?</p>
    <a href="{% url 'login' %}">Đăng nhập</a>
</div>
{% endif %}

{% endblock content %}

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'base/topics_component.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="{{user.avatar.url}}" />
          </div>
        </div>
        <div class="profile__info">
          <h3>{{user.name}}</h3>
          <p>@{{user.username}}</p>
          {% if request.user == user %}
          <a href="{% url 'update-user' %}" class="btn btn--main btn--pill">Chỉnh sửa hồ sơ</a>
          {% endif %}
        </div>
        <div class="profile__about">
          <h3>Giới thiệu</h3>
          <p>
            {{user.bio}}
          </p>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Các phòng do {{user.username}} tạo</h2>
        </div>
      </div>
      {% include 'base/feed_component.html' %}


    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

base/templates/base/profile_old.html
{% extends 'main.html' %}

{% block content %}

<style>
    .profile-container {
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<h1>{{user.username}}</h1>

<div class="profile-container">
    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        {% include 'base/feed_component.html' %}
    </div>

    <div>
        {% include 'base/activity_component.html' %}
    </div>
</div>

{% endblock content %}

base/templates/base/room_form_old.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" />
    </form>
</div>

{% endblock content %}

base/templates/base/topics_component.html
<div class="topics">
    <div class="topics__header">
        <h2>Chủ đề thảo luận</h2>
    </div>
    <ul class="topics__list">
        <li>
            <a href="{% url 'home' %}" class="active">Tất cả <span>{{topics.count}}</span></a>
        </li>
        {% for topic in topics %}
        <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
        </li>
        {% endfor %}

    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
        Xem thêm
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
    </a>
</div>